sudo: false
language: node_js
node_js:
  - "4.9.1"
  - "6.14.1"
  - "8.11.1"
  - "9.11.1"
# matrix:
#   include:
#     - node_js: "4.0"
#       env: BROWSER=true
before_install:
  - npm i -g npm
install:
  - npm install
script:
  - npm test
notifications:
    email: false
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
after_success: npm run coveralls
